import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __codegen_dir = resolve(__filename, '..')
const SPEC_PATH = resolve(__codegen_dir, '../../../spec/openapi-frontend.json')
const OUTPUT_PATH = resolve(__codegen_dir, '../src/generated/frontend-paths.ts')

type SpecOperation = { operationId?: string }
type SpecPaths = Record<string, Record<string, SpecOperation>>

function main() {
  const spec = JSON.parse(readFileSync(SPEC_PATH, 'utf-8')) as { paths?: SpecPaths }
  const paths = spec.paths ?? {}

  const entries: Array<[string, string]> = []
  for (const [path, methods] of Object.entries(paths)) {
    for (const operation of Object.values(methods)) {
      const operationId = operation?.operationId
      if (typeof operationId === 'string' && operationId.length > 0) {
        entries.push([operationId, path])
      }
    }
  }
  entries.sort((a, b) => a[0].localeCompare(b[0]))

  const lines: string[] = []
  lines.push('/**')
  lines.push(' * This file was auto-generated by codegen/generate-frontend-paths.ts.')
  lines.push(' * Do not make direct changes to the file.')
  lines.push(' */')
  lines.push('')
  lines.push("import type { operations } from './frontend-api-types'")
  lines.push('')
  lines.push('export const FRONTEND_PATHS = {')
  for (const [operationId, path] of entries) {
    lines.push(`  ${operationId}: '${path}',`)
  }
  lines.push('} satisfies Record<keyof operations, string>')
  lines.push('')
  lines.push('export type FrontendOperationId = keyof typeof FRONTEND_PATHS')
  lines.push('')

  writeFileSync(OUTPUT_PATH, lines.join('\n'), 'utf-8')
  console.log(`Generated frontend-paths.ts (${entries.length} operations)`)
}

main()
