/*
 * Automatically generated using TypeScript API.
 * Please do not edit this file directly.
 */

export type GenerateAnalyticsRequestType = { query: { time_label_format?: "12h" | "24h" | undefined; week_first_day?: "S" | "M" | undefined; conversation_id?: string | undefined; conversation_reference?: string | undefined; message_reference?: string | undefined; message_id?: string | undefined; }; };

export type CreateAnalyticsReportFileRequestType = { query: { query: { time_label_format?: "12h" | "24h" | undefined; week_first_day?: "S" | "M" | undefined; conversation_id?: string | undefined; conversation_reference?: string | undefined; message_reference?: string | undefined; message_id?: string | undefined; }; } & { document: { send_as_link: boolean; title?: string | undefined; author?: string | undefined; subject?: string | undefined; keywords?: string | undefined; password?: string | undefined; orientation: "portrait" | "landscape"; page_size: "A0" | "A1" | "A2" | "A3" | "A4" | "A5" | "A6" | "A7" | "A8" | "A9" | "A10" | "B0" | "B1" | "B2" | "B3" | "B4" | "B5" | "B6" | "B7" | "B8" | "B9" | "B10" | "C0" | "C1" | "C2" | "C3" | "C4" | "C5" | "C6" | "C7" | "C8" | "C9" | "C10" | "RA0" | "RA1" | "RA2" | "RA3" | "RA4" | "SRA0" | "SRA1" | "SRA2" | "SRA3" | "SRA4"; margin: (number | { top: number; left: number; right: number; bottom: number; } | undefined) & (number | { top: number; left: number; right: number; bottom: number; }); version: "1.3" | "1.4" | "1.5" | "1.6" | "1.7" | "1.7ext3"; }; }; };
