/*
 * Automatically generated using TypeScript API.
 * Please do not edit this file directly.
 */

export type ReservePhoneNumberRequestType = { phone_number: string; };

export type CreatePrivatePhoneNumbersRequestType = { phone_numbers: { type: "VIRTUAL_LONG_NUMBER" | "10_DLC" | "SHORT_CODE" | "SHORT_CODE_USSD"; channels: ("SMS" | "OTP")[]; is_default_sender: boolean; is_general_sender: boolean; phone_number: string; coverage: "LOCAL" | "INTERNATIONAL"; is_conjoin_sender: boolean; reference_id?: string | undefined; registrar_id?: string | undefined; country_iso?: string | undefined; }[]; };

export type FetchAvailablePhoneNumbersRequestType = unknown

export type FetchReservedPhoneNumbersRequestType = unknown

export type FetchPrivateReservedPhoneNumbersRequestType = unknown

export type ReleasePhoneNumbersRequestType = unknown

export type DeletePhoneNumbersRequestType = { filters: { reference_id?: string | { $equals?: string; $ne?: string; $length?: number; $regex?: RegExp; $in?: Array<string>; $nin?: Array<string>; $gt?: string; $lt?: string; $gte?: string; $lte?: string; } | undefined; phone_number?: string | { $equals?: string; $ne?: string; $length?: number; $regex?: RegExp; $in?: Array<string>; $nin?: Array<string>; $gt?: string; $lt?: string; $gte?: string; $lte?: string; } | undefined; phone_number_id?: string | { $equals?: string; $ne?: string; $length?: number; $regex?: RegExp; $in?: Array<string>; $nin?: Array<string>; $gt?: string; $lt?: string; $gte?: string; $lte?: string; } | undefined; }; };
