/*
 * Automatically generated using TypeScript API.
 * Please do not edit this file directly.
 */

export type RegisterBrandRequestType = { entity_type: "PRIVATE_PROFIT" | "PUBLIC_PROFIT" | "GOVERNMENT" | "NON_PROFIT" | "SOLE_PROPRIETOR"; display_name: string; legal_name?: string | undefined; country_code: string; state: string; city: string; street: string; zip_code: string; support_phone: string; mobile_phone?: string | undefined; website?: string | undefined; vertical: "AGRICULTURE" | "CONSTRUCTION_AND_MATERIALS" | "EDUCATION" | "ENERGY_AND_UTILITIES" | "ENTERTAINMENT" | "FINANCIAL_SERVICES" | "GAMBLING_AND_LOTTERY" | "HEALTHCARE_AND_LIFE_SCIENCES" | "HOSPITALITY_AND_TRAVEL" | "HR_STAFFING_AND_RECRUITMENT" | "INFORMATION_TECHNOLOGY_SERVICES" | "INSURANCE" | "LEGAL" | "MANUFACTURING" | "MEDIA_AND_COMMUNICATIONS" | "NON_PROFIT_ORGANIZATION" | "POLITICAL" | "POSTAL_AND_DELIVERY" | "PROFESSIONAL_SERVICES" | "PUBLIC_SECTOR" | "REAL_ESTATE" | "RETAIL_AND_CONSUMER_PRODUCTS" | "TRANSPORTATION_AND_LOGISTICS"; alternate_business_id?: string | undefined; alternate_business_id_type?: "DUNS" | "LEI" | "GIIN" | undefined; tax_id: string; tax_id_issuer: string; };

export type FetchBrandsRequestType = {};

export type UpdateBrandDetailsRequestType = {};

export type DeleteBrandsRequestType = {};
