/*
 * Automatically generated using TypeScript API.
 * Please do not edit this file directly.
 */

export type CreateSmsAlphanumericSenderRequestType = { reference_id?: string | undefined; sender: string; country_iso?: string | undefined; is_default_sender: boolean; };

export type CreatePrivateSmsAlphanumericSenderRequestType = { reference_id?: string | undefined; sender: string; country_iso?: string | undefined; is_default_sender: boolean; } & { country_iso?: string | undefined; registrar_id?: string | undefined; is_general_sender: boolean; status: "TRANSFERING" | "ACTIVE" | "DISABLED" | "VERIFYING" | "UNVERIFIED" | "AVAILABLE"; };

export type ActivateSmsAlphanumericSenderRequestType = { sender_id: string; };

export type ActivatePrivateSmsAlphanumericSenderRequestType = { sender_id?: string | undefined; };

export type DisableSmsAlphanumericSenderRequestType = { sender_id: string; };

export type DisablePrivateSmsAlphanumericSenderRequestType = { sender_id?: string | undefined; };

export type DeleteSmsAlphanumericSenderRequestType = { sender_id: string; };

export type DeletePrivateSmsAlphanumericSenderRequestType = { sender_id: string; };
