/*
 * Automatically generated using TypeScript API.
 * Please do not edit this file directly.
 */

export type CreateBillingProductRequestType = { name: string; unit_label: string; reference_id?: string | undefined; statement_descriptor?: string | undefined; description?: string | undefined; is_active?: boolean | undefined; custom_metadata?: Record<string, string | number | null> | undefined; images?: string[] | undefined; features?: { name: string; description?: string | undefined; }[] | undefined; };

export type UpdateBillingProductRequestType = { name?: string | undefined; statement_descriptor?: string | undefined; description?: string | undefined; is_active?: boolean | undefined; custom_metadata?: Record<string, string | number | null> | undefined; unit_label?: string | undefined; images?: string[] | undefined; features?: { name: string; description?: string | undefined; }[] | undefined; };

export type ReadBillingProductRequestType = { limit: number; record_date_created?: unknown; record_date_updated?: unknown; record_date_deleted?: unknown; sort?: Partial<Record<"record_date_created" | "record_date_updated" | "name" | "reference_id" | "statement_descriptor" | "description" | "is_active" | "product_id" | "unit_label" | "images" | "features", 1 | -1>> | { record_date_created: string; } | undefined; query_cursor?: string | undefined; name?: unknown; description?: unknown; is_active?: boolean | undefined; };
