/*
 * Automatically generated using TypeScript API.
 * Please do not edit this file directly.
 */

export type CreateBillingRefundRequestType = { reference_id: string; charge_id: string; amount?: number | undefined; };

export type ReadBillingRefundRequestType = { entity_id: string; limit: number; refund_id: string; record_date_created?: unknown; record_date_updated?: unknown; record_date_deleted?: unknown; sort?: Partial<Record<"status" | "amount" | "currency" | "charge_id" | "refund_id" | "fulfilment_type", 1 | -1>> | { record_date_created: string; } | undefined; include?: ("status" | "amount" | "currency" | "charge_id" | "refund_id" | "fulfilment_type")[] | undefined; query_cursor?: string | undefined; reference_id?: unknown; };
