from __future__ import annotations

import shutil
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from codegen.ir import Operation, ResourceGroup
from codegen.naming import (
    pluralize,
    resource_attribute_name,
    strip_v1,
    to_pascal,
    to_snake,
)
from codegen.schema import (
    FieldDef,
    ModelDef,
    TypedDictDef,
    is_object_schema,
    model_from_schema,
    schema_annotation,
    typed_dict_from_schema,
    union_with_none,
)

HEADER = "# Code generated by sdks/python/codegen; DO NOT EDIT.\n\n"
OUTPUT_ROOT = Path(__file__).resolve().parents[1] / "src" / "conjoin_cloud" / "generated"


@dataclass(frozen=True)
class MethodEntry:
    operation: Operation
    method_name: str
    base_name: str
    response_type: str
    response_model: str | None
    body_type: str | None
    query_type: str | None


def render_all(groups: tuple[ResourceGroup, ...], output_root: Path = OUTPUT_ROOT) -> None:
    if output_root.exists():
        shutil.rmtree(output_root)
    output_root.mkdir(parents=True)

    rendered_groups: list[tuple[ResourceGroup, tuple[MethodEntry, ...]]] = []
    models: dict[str, ModelDef] = {}
    typed_dicts: dict[str, TypedDictDef] = {}

    for group in groups:
        entries = resolve_method_entries(group)
        rendered_groups.append((group, entries))
        for entry in entries:
            if entry.response_model is not None:
                models[entry.response_model] = model_from_schema(
                    entry.response_model,
                    _response_model_schema(entry.operation),
                )
            if entry.body_type is not None and entry.operation.request_schema is not None:
                typed_dicts[entry.body_type] = typed_dict_from_schema(
                    entry.body_type,
                    entry.operation.request_schema,
                )
            if entry.query_type is not None:
                typed_dicts[entry.query_type] = TypedDictDef(
                    name=entry.query_type,
                    fields=tuple(
                        _parameter_field(
                            parameter.name,
                            parameter.schema,
                            required=parameter.required,
                        )
                        for parameter in entry.operation.query_parameters
                    ),
                )

    _write(
        output_root / "_models.py",
        _render_models(tuple(models.values()), tuple(typed_dicts.values())),
    )

    for group, entries in sorted(rendered_groups, key=lambda item: _group_sort_key(item[0])):
        service_dir = output_root / to_snake(group.service)
        service_dir.mkdir(parents=True, exist_ok=True)
        _write(
            service_dir / f"_{to_snake(group.resource)}.py",
            _render_resource_module(group, entries),
        )

    services = _services(rendered_groups)
    for service, service_groups in services:
        _write(
            output_root / to_snake(service) / "__init__.py",
            _render_service_module(service, service_groups),
        )

    _write(output_root / "_client_mixins.py", _render_client_mixins(services))
    _write(output_root / "__init__.py", _render_generated_init(services))


def resolve_method_entries(group: ResourceGroup) -> tuple[MethodEntry, ...]:
    names = [operation.method_name for operation in group.operations]
    counts = _counts(names)
    resolved: list[tuple[str, Operation]] = []
    for operation in group.operations:
        name = operation.method_name
        if counts[name] > 1:
            if operation.is_list_response:
                name = "list" if name in {"get", "read"} else f"list_{name}"
            elif operation.operation_id.find(pluralize(group.resource_pascal)) >= 0:
                name = to_snake(pluralize(name))
        resolved.append((name, operation))

    final_counts = _counts(name for name, _operation in resolved)
    entries: list[MethodEntry] = []
    for name, operation in resolved:
        method_name = to_snake(operation.operation_id) if final_counts[name] > 1 else to_snake(name)
        base_name = f"{group.service_pascal}{group.resource_pascal}{to_pascal(method_name)}"
        response_model = _response_model_name(operation, base_name)
        entries.append(
            MethodEntry(
                operation=operation,
                method_name=method_name,
                base_name=base_name,
                response_type=_response_type(operation, response_model),
                response_model=response_model,
                body_type=_body_type(operation, base_name),
                query_type=_query_type(operation, base_name),
            )
        )
    return tuple(entries)


def _render_models(
    models: tuple[ModelDef, ...],
    typed_dicts: tuple[TypedDictDef, ...],
) -> str:
    lines = [
        "from __future__ import annotations",
        "",
        "from collections.abc import Sequence",
        "from typing import Any, TypedDict",
        "",
        "from pydantic import Field",
        "",
        "from conjoin_cloud._models import ConjoinModel",
        "",
        "",
    ]
    for model in sorted(models, key=lambda item: item.name):
        lines.extend(_render_model(model))
        lines.extend(["", ""])
    for typed_dict in sorted(typed_dicts, key=lambda item: item.name):
        lines.extend(_render_typed_dict(typed_dict))
        lines.extend(["", ""])
    return HEADER + "\n".join(lines).rstrip() + "\n"


def _render_model(model: ModelDef) -> list[str]:
    lines = [f"class {model.name}(ConjoinModel):"]
    if not model.fields:
        return [*lines, "    pass"]
    for field in model.fields:
        annotation = field.annotation if field.required else union_with_none(field.annotation)
        if field.wire_name == field.python_name:
            default = "" if field.required else " = None"
            lines.append(f"    {field.python_name}: {annotation}{default}")
            continue
        default_expr = "..." if field.required else "None"
        lines.extend(
            _field_assignment_lines(field.python_name, annotation, default_expr, field.wire_name)
        )
    return lines


def _render_typed_dict(typed_dict: TypedDictDef) -> list[str]:
    required_fields = tuple(field for field in typed_dict.fields if field.required)
    optional_fields = tuple(field for field in typed_dict.fields if not field.required)
    if not typed_dict.fields:
        lines = _class_header(typed_dict.name, ("TypedDict", "total=False"))
        return [*lines, "    pass"]

    if required_fields and optional_fields:
        required_name = f"_{typed_dict.name}Required"
        lines = _class_header(required_name, ("TypedDict",))
        lines.extend(f"    {field.python_name}: {field.annotation}" for field in required_fields)
        lines.extend(["", *_class_header(typed_dict.name, (required_name, "total=False"))])
        lines.extend(f"    {field.python_name}: {field.annotation}" for field in optional_fields)
        return lines

    bases = ("TypedDict",) if required_fields else ("TypedDict", "total=False")
    lines = _class_header(typed_dict.name, bases)
    for field in typed_dict.fields:
        lines.append(f"    {field.python_name}: {field.annotation}")
    return lines


def _class_header(name: str, bases: tuple[str, ...]) -> list[str]:
    line = f"class {name}({', '.join(bases)}):"
    if len(line) <= 100:
        return [line]
    return [f"class {name}(", *(f"    {base}," for base in bases), "):"]


def _render_resource_module(group: ResourceGroup, entries: tuple[MethodEntry, ...]) -> str:
    class_base = f"{group.service_pascal}{pluralize(group.resource_pascal)}"
    lines = [
        "from __future__ import annotations",
        "",
        "from collections.abc import Mapping",
        "from typing import TYPE_CHECKING, Any",
    ]
    if any(entry.operation.path_parameters for entry in entries):
        lines.append("from urllib.parse import quote")
    lines.append("")
    if any(_needs_configuration_error(entry.operation) for entry in entries):
        lines.append("from conjoin_cloud._errors import ConjoinConfigurationError")
    if any(entry.response_type.startswith("Page[") for entry in entries):
        lines.append("from conjoin_cloud._models import Page")
    if any(entry.operation.request_content_type == "multipart/form-data" for entry in entries):
        lines.append("from conjoin_cloud._multipart import MultipartBody")
    if any(_needs_options_helper(entry.operation) for entry in entries):
        lines.append(
            "from conjoin_cloud._request_options import RequestOptions, coerce_request_options"
        )
    else:
        lines.append("from conjoin_cloud._request_options import RequestOptions")
    model_imports = _model_imports(entries)
    if model_imports:
        lines.append("from conjoin_cloud.generated._models import (")
        lines.extend(f"    {name}," for name in model_imports)
        lines.append(")")
    lines.extend(
        [
            "",
            "if TYPE_CHECKING:",
            "    from conjoin_cloud import AsyncConjoin, Conjoin",
            "",
            "",
        ]
    )
    lines.extend(_render_alias_constants(entries))
    if any(_body_aliases(entry) or _query_aliases(entry) for entry in entries):
        lines.extend(["", ""])

    lines.extend(
        _render_resource_class(
            class_name=f"{class_base}Resource",
            client_type="Conjoin",
            entries=entries,
            is_async=False,
        )
    )
    lines.extend(["", ""])
    lines.extend(
        _render_resource_class(
            class_name=f"Async{class_base}Resource",
            client_type="AsyncConjoin",
            entries=entries,
            is_async=True,
        )
    )
    lines.extend(_render_helpers(entries))
    return HEADER + "\n".join(lines).rstrip() + "\n"


def _render_resource_class(
    *,
    class_name: str,
    client_type: str,
    entries: tuple[MethodEntry, ...],
    is_async: bool,
) -> list[str]:
    lines = [
        f"class {class_name}:",
        "    def __init__(",
        "        self,",
        f"        client: {client_type},",
        "        *,",
        "        profile_id: str | None = None,",
        "        scim_token: str | None = None,",
        "    ) -> None:",
        "        self._client = client",
        "        self._profile_id = profile_id",
        "        self._scim_token = scim_token",
    ]
    if any(entry.operation.auth_mode == "scim_bearer" for entry in entries):
        lines.extend(
            [
                "",
                f"    def with_token(self, scim_token: str) -> {class_name}:",
                f"        return {class_name}(self._client, scim_token=scim_token)",
            ]
        )
    for entry in entries:
        lines.append("")
        lines.extend(_render_method(entry, is_async=is_async))
    return lines


def _render_method(entry: MethodEntry, *, is_async: bool) -> list[str]:
    operation = entry.operation
    async_prefix = "async " if is_async else ""
    await_prefix = "await " if is_async else ""
    lines = [f"    {async_prefix}def {entry.method_name}("]
    lines.append("        self,")
    lines.extend(f"        {parameter}," for parameter in _method_parameters(entry))
    lines.append("        *,")
    lines.append("        request_options: RequestOptions | Mapping[str, Any] | None = None,")
    lines.append(f"    ) -> {entry.response_type}:")
    if operation.requires_messaging_profile:
        lines.append("        profile_id = _require_messaging_profile(self._profile_id)")
    if operation.auth_mode == "scim_bearer":
        lines.append(
            "        request_options = _with_scim_bearer(request_options, self._scim_token)"
        )
    elif operation.auth_mode == "none":
        lines.append("        request_options = _with_auth_none(request_options)")
    if operation.requires_messaging_profile:
        lines.append(
            "        request_options = _with_messaging_profile(request_options, profile_id)"
        )

    lines.append(f"        return {await_prefix}self._client.request(")
    lines.append(f"            {operation.http_method!r},")
    lines.append(f"            {_path_expression(operation)},")
    lines.append(f"            query={_query_expression(entry)},")
    lines.append(f"            body={_body_expression(entry)},")
    lines.append(f"            cast_to={_cast_expression(entry)},")
    lines.append("            request_options=request_options,")
    lines.append("        )")
    return lines


def _render_service_module(
    service: str,
    service_groups: tuple[ResourceGroup, ...],
) -> str:
    service_pascal = to_pascal(service)
    lines = [
        "from __future__ import annotations",
        "",
        "from typing import TYPE_CHECKING",
        "",
    ]
    for group in service_groups:
        class_base = f"{group.service_pascal}{pluralize(group.resource_pascal)}"
        module_name = to_snake(group.resource)
        lines.append(f"from conjoin_cloud.generated.{to_snake(service)}._{module_name} import (")
        lines.append(f"    Async{class_base}Resource,")
        lines.append(f"    {class_base}Resource,")
        lines.append(")")
    lines.extend(
        [
            "",
            "if TYPE_CHECKING:",
            "    from conjoin_cloud import AsyncConjoin, Conjoin",
            "",
            "",
            f"class {service_pascal}Resource:",
            "    def __init__(self, client: Conjoin, *, profile_id: str | None = None) -> None:",
            "        self._client = client",
            "        self._profile_id = profile_id",
        ]
    )
    for group in service_groups:
        attr = resource_attribute_name(group.resource)
        class_base = f"{group.service_pascal}{pluralize(group.resource_pascal)}Resource"
        lines.extend(
            _assignment_lines(f"self.{attr}", f"{class_base}(client, profile_id=profile_id)")
        )
    if service == "messaging":
        lines.extend(
            [
                "",
                f"    def with_profile(self, profile_id: str) -> {service_pascal}Resource:",
                f"        return {service_pascal}Resource(self._client, profile_id=profile_id)",
            ]
        )

    lines.extend(
        [
            "",
            "",
            f"class Async{service_pascal}Resource:",
            "    def __init__(",
            "        self,",
            "        client: AsyncConjoin,",
            "        *,",
            "        profile_id: str | None = None,",
            "    ) -> None:",
            "        self._client = client",
            "        self._profile_id = profile_id",
        ]
    )
    for group in service_groups:
        attr = resource_attribute_name(group.resource)
        class_base = f"Async{group.service_pascal}{pluralize(group.resource_pascal)}Resource"
        lines.extend(
            _assignment_lines(f"self.{attr}", f"{class_base}(client, profile_id=profile_id)")
        )
    if service == "messaging":
        lines.extend(
            [
                "",
                f"    def with_profile(self, profile_id: str) -> Async{service_pascal}Resource:",
                (
                    f"        return Async{service_pascal}Resource("
                    "self._client, profile_id=profile_id)"
                ),
            ]
        )
    lines.append("")
    return HEADER + "\n".join(lines)


def _render_client_mixins(
    services: tuple[tuple[str, tuple[ResourceGroup, ...]], ...],
) -> str:
    lines = [
        "from __future__ import annotations",
        "",
        "from typing import Any",
        "",
    ]
    for service, _groups in services:
        service_pascal = to_pascal(service)
        lines.append(
            f"from conjoin_cloud.generated.{to_snake(service)} import "
            f"Async{service_pascal}Resource, {service_pascal}Resource"
        )
    lines.extend(["", "", "class SyncGeneratedResourcesMixin:"])
    for service, _groups in services:
        lines.append(f"    {to_snake(service)}: {to_pascal(service)}Resource")
    lines.extend(["", "    def _init_generated_resources(self: Any) -> None:"])
    for service, _groups in services:
        lines.append(f"        self.{to_snake(service)} = {to_pascal(service)}Resource(self)")
    lines.extend(["", "", "class AsyncGeneratedResourcesMixin:"])
    for service, _groups in services:
        lines.append(f"    {to_snake(service)}: Async{to_pascal(service)}Resource")
    lines.extend(["", "    def _init_generated_resources(self: Any) -> None:"])
    for service, _groups in services:
        lines.append(
            f"        self.{to_snake(service)} = Async{to_pascal(service)}Resource(self)"
        )
    lines.append("")
    return HEADER + "\n".join(lines)


def _render_generated_init(
    services: tuple[tuple[str, tuple[ResourceGroup, ...]], ...],
) -> str:
    names: list[str] = ["AsyncGeneratedResourcesMixin", "SyncGeneratedResourcesMixin"]
    lines = [
        "from conjoin_cloud.generated._client_mixins import (",
        "    AsyncGeneratedResourcesMixin,",
        "    SyncGeneratedResourcesMixin,",
        ")",
    ]
    for service, _groups in services:
        service_pascal = to_pascal(service)
        lines.append(
            f"from conjoin_cloud.generated.{to_snake(service)} import "
            f"Async{service_pascal}Resource, {service_pascal}Resource"
        )
        names.extend([f"Async{service_pascal}Resource", f"{service_pascal}Resource"])
    lines.extend(["", "__all__ = ("])
    lines.extend(f"    {name!r}," for name in sorted(names))
    lines.extend([")", ""])
    return HEADER + "\n".join(lines)


def _render_helpers(entries: tuple[MethodEntry, ...]) -> list[str]:
    lines: list[str] = []
    if any(_body_aliases(entry) or _query_aliases(entry) for entry in entries):
        lines.extend(
            [
                "",
                "",
                "def _wire_body(",
                "    value: Mapping[str, Any],",
                "    aliases: Mapping[str, str],",
                ") -> dict[str, Any]:",
                "    mapped = dict(value)",
                "    for python_name, wire_name in aliases.items():",
                "        if python_name in mapped and wire_name not in mapped:",
                "            mapped[wire_name] = mapped.pop(python_name)",
                "    return mapped",
                "",
                "",
                "def _wire_mapping(",
                "    value: Mapping[str, Any] | None,",
                "    aliases: Mapping[str, str],",
                ") -> dict[str, Any] | None:",
                "    if value is None:",
                "        return None",
                "    mapped = dict(value)",
                "    for python_name, wire_name in aliases.items():",
                "        if python_name in mapped and wire_name not in mapped:",
                "            mapped[wire_name] = mapped.pop(python_name)",
                "    return mapped",
            ]
        )
    if any(entry.operation.requires_messaging_profile for entry in entries):
        lines.extend(
            [
                "",
                "",
                "def _require_messaging_profile(profile_id: str | None) -> str:",
                "    if profile_id is None or not profile_id.strip():",
                "        raise ConjoinConfigurationError(",
                "            \"Messaging profile scope is required; \"",
                "            \"call client.messaging.with_profile(...)\"",
                "        )",
                "    return profile_id.strip()",
                "",
                "",
                "def _with_messaging_profile(",
                "    request_options: RequestOptions | Mapping[str, Any] | None,",
                "    profile_id: str,",
                ") -> RequestOptions:",
                "    options = coerce_request_options(request_options)",
                "    headers = dict(options.headers or {})",
                "    headers[\"Messaging-Profile-ID\"] = profile_id",
                "    return RequestOptions(",
                "        timeout=options.timeout,",
                "        max_retries=options.max_retries,",
                "        conjoin_request_id=options.conjoin_request_id,",
                "        headers=headers,",
                "        auth=options.auth,",
                "    )",
            ]
        )
    if any(entry.operation.path_parameters for entry in entries):
        lines.extend(
            [
                "",
                "",
                "def _encode_path_param(value: str) -> str:",
                "    return quote(value, safe=\"\")",
            ]
        )
    if any(entry.operation.auth_mode == "scim_bearer" for entry in entries):
        lines.extend(
            [
                "",
                "",
                "def _with_scim_bearer(",
                "    request_options: RequestOptions | Mapping[str, Any] | None,",
                "    scim_token: str | None,",
                ") -> RequestOptions:",
                "    if scim_token is None or not scim_token.strip():",
                "        raise ConjoinConfigurationError(",
                "            \"SCIM token is required for tenant SCIM operations\"",
                "        )",
                "    options = coerce_request_options(request_options)",
                "    return RequestOptions(",
                "        timeout=options.timeout,",
                "        max_retries=options.max_retries,",
                "        conjoin_request_id=options.conjoin_request_id,",
                "        headers=options.headers,",
                "        auth={\"type\": \"bearer\", \"token\": scim_token.strip()},",
                "    )",
            ]
        )
    if any(entry.operation.auth_mode == "none" for entry in entries):
        lines.extend(
            [
                "",
                "",
                "def _with_auth_none(",
                "    request_options: RequestOptions | Mapping[str, Any] | None,",
                ") -> RequestOptions:",
                "    options = coerce_request_options(request_options)",
                "    return RequestOptions(",
                "        timeout=options.timeout,",
                "        max_retries=options.max_retries,",
                "        conjoin_request_id=options.conjoin_request_id,",
                "        headers=options.headers,",
                "        auth={\"type\": \"none\"},",
                "    )",
            ]
        )
    return lines


def _method_parameters(entry: MethodEntry) -> list[str]:
    operation = entry.operation
    parameters = [f"{parameter.python_name}: str" for parameter in operation.path_parameters]
    if entry.body_type is not None:
        parameters.append(f"data: {entry.body_type}")
    elif operation.has_request_body:
        parameters.append("data: Mapping[str, Any]")
    if entry.query_type is not None:
        parameters.append(f"query: {entry.query_type} | None = None")
    elif operation.query_parameters:
        parameters.append("query: Mapping[str, Any] | None = None")
    return parameters


def _body_expression(entry: MethodEntry) -> str:
    operation = entry.operation
    if not operation.has_request_body:
        return "None"
    aliases = _body_aliases(entry)
    data_expression = "data" if not aliases else f"_wire_body(data, {_alias_name(entry, 'body')})"
    if operation.request_content_type == "multipart/form-data":
        return f"MultipartBody({data_expression})"
    return data_expression


def _query_expression(entry: MethodEntry) -> str:
    aliases = _query_aliases(entry)
    if not entry.operation.query_parameters:
        return "None"
    return "query" if not aliases else f"_wire_mapping(query, {_alias_name(entry, 'query')})"


def _cast_expression(entry: MethodEntry) -> str:
    if entry.response_type == "Any":
        return "None"
    return entry.response_type


def _path_expression(operation: Operation) -> str:
    path = strip_v1(operation.path)
    if not operation.path_parameters:
        return repr(path)
    for parameter in operation.path_parameters:
        path = path.replace(
            f"{{{parameter.name}}}",
            f"{{_encode_path_param({parameter.python_name})}}",
        )
    return f"f{path!r}"


def _response_type(operation: Operation, model_name: str | None) -> str:
    if operation.is_list_response:
        return f"Page[{model_name}]" if model_name is not None else "Page[Any]"
    return model_name if model_name is not None else "Any"


def _response_model_name(operation: Operation, base_name: str) -> str | None:
    schema = _response_model_schema(operation)
    if not is_object_schema(schema):
        return None
    suffix = "Item" if operation.is_list_response else "Response"
    return f"{base_name}{suffix}"


def _response_model_schema(operation: Operation) -> dict[str, Any]:
    if operation.has_data_property:
        return operation.response_data_schema
    return operation.response_schema


def _body_type(operation: Operation, base_name: str) -> str | None:
    if operation.request_schema is not None and is_object_schema(operation.request_schema):
        return f"{base_name}Request"
    return None


def _query_type(operation: Operation, base_name: str) -> str | None:
    return f"{base_name}Query" if operation.query_parameters else None


def _body_aliases(entry: MethodEntry) -> dict[str, str]:
    schema = entry.operation.request_schema
    if schema is None:
        return {}
    properties = schema.get("properties")
    if not isinstance(properties, dict):
        return {}
    return _aliases(properties)


def _query_aliases(entry: MethodEntry) -> dict[str, str]:
    names = {parameter.name: parameter.schema for parameter in entry.operation.query_parameters}
    return _aliases(names)


def _aliases(fields: dict[str, Any]) -> dict[str, str]:
    aliases: dict[str, str] = {}
    for wire_name in sorted(fields):
        python_name = to_snake(wire_name)
        if python_name != wire_name:
            aliases[python_name] = wire_name
    return aliases


def _parameter_field(name: str, schema: dict[str, Any], *, required: bool) -> FieldDef:
    return FieldDef(
        wire_name=name,
        python_name=to_snake(name),
        annotation=schema_annotation(schema),
        required=required,
    )


def _field_assignment_lines(
    python_name: str,
    annotation: str,
    default_expr: str,
    alias: str,
) -> list[str]:
    line = f"    {python_name}: {annotation} = Field({default_expr}, alias={alias!r})"
    if len(line) <= 100:
        return [line]
    return [
        f"    {python_name}: {annotation} = Field(",
        f"        {default_expr},",
        f"        alias={alias!r},",
        "    )",
    ]


def _render_alias_constants(entries: tuple[MethodEntry, ...]) -> list[str]:
    lines: list[str] = []
    for entry in entries:
        for kind, aliases in (("body", _body_aliases(entry)), ("query", _query_aliases(entry))):
            if not aliases:
                continue
            lines.append(f"{_alias_name(entry, kind)} = {{")
            for python_name, wire_name in aliases.items():
                lines.append(f"    {python_name!r}: {wire_name!r},")
            lines.append("}")
    return lines


def _alias_name(entry: MethodEntry, kind: str) -> str:
    return f"_{entry.method_name.upper()}_{kind.upper()}_ALIASES"


def _assignment_lines(target: str, expression: str) -> list[str]:
    line = f"        {target} = {expression}"
    if len(line) <= 100:
        return [line]
    call = expression.split("(", 1)[0]
    return [
        f"        {target} = {call}(",
        "            client,",
        "            profile_id=profile_id,",
        "        )",
    ]


def _model_imports(entries: tuple[MethodEntry, ...]) -> tuple[str, ...]:
    names: set[str] = set()
    for entry in entries:
        if entry.response_model is not None:
            names.add(entry.response_model)
        if entry.body_type is not None:
            names.add(entry.body_type)
        if entry.query_type is not None:
            names.add(entry.query_type)
    return tuple(sorted(names))


def _services(
    rendered_groups: list[tuple[ResourceGroup, tuple[MethodEntry, ...]]],
) -> tuple[tuple[str, tuple[ResourceGroup, ...]], ...]:
    services: dict[str, list[ResourceGroup]] = {}
    for group, _entries in rendered_groups:
        services.setdefault(group.service, []).append(group)
    return tuple(
        (service, tuple(sorted(groups, key=lambda group: group.resource)))
        for service, groups in sorted(services.items())
    )


def _counts(values: Iterable[str]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for value in values:
        counts[value] = counts.get(value, 0) + 1
    return counts


def _group_sort_key(group: ResourceGroup) -> tuple[str, str]:
    return group.service, group.resource


def _needs_configuration_error(operation: Operation) -> bool:
    return operation.requires_messaging_profile or operation.auth_mode == "scim_bearer"


def _needs_options_helper(operation: Operation) -> bool:
    return (
        operation.requires_messaging_profile
        or operation.auth_mode == "none"
        or operation.auth_mode == "scim_bearer"
    )


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
