import {
  CHARGE_ID,
  COUPON_ID,
  CREDIT_NOTE_ID,
  CUSTOMER_ID,
  DATE_CREATED,
  DATE_UPDATED,
  DISCOUNT_ID,
  ENTITY_ID,
  INVOICE_ID,
  PAYMENT_INTENT_ID,
  PAYMENT_METHOD_ID,
  PRICE_ID,
  RECEIPT_ID,
  REFUND_ID,
  WALLET_ID,
} from './billing-test-utils'

export const billingChargeFixture = (overrides: Record<string, unknown> = {}) => ({
  amount: 1000,
  charge_id: CHARGE_ID,
  currency: 'GHS',
  date_created: DATE_CREATED,
  date_updated: DATE_UPDATED,
  entity_id: ENTITY_ID,
  payment_type: 'invoice',
  status: 'success',
  transaction_id: 'transaction_123',
  transaction_type: 'payment',
  ...overrides,
})

export const billingCouponFixture = (overrides: Record<string, unknown> = {}) => ({
  amount_off: null,
  applies_to: {
    price_ids: [],
    product_ids: [],
    scope: 'all_items',
  },
  conjoin_account_id: 'account_123',
  conjoin_project_id: 'project_123',
  coupon_code: 'SAVE10',
  coupon_id: COUPON_ID,
  currency: null,
  date_created: DATE_CREATED,
  date_updated: DATE_UPDATED,
  discount_type: 'percent_off',
  duration: 'once',
  duration_in_cycles: null,
  expiration_date: null,
  is_active: true,
  live_mode: false,
  max_redemptions: null,
  name: 'Save 10',
  percent_off: 10,
  reason_code: 'promotion',
  reference_id: 'coupon_reference_123',
  times_redeemed: 0,
  ...overrides,
})

export const billingCreditNoteFixture = (overrides: Record<string, unknown> = {}) => ({
  amount: 500,
  amount_remaining: 500,
  applications: [],
  conjoin_account_id: 'account_123',
  conjoin_project_id: 'project_123',
  credit_note_id: CREDIT_NOTE_ID,
  currency: 'GHS',
  customer_id: CUSTOMER_ID,
  date_created: DATE_CREATED,
  date_updated: DATE_UPDATED,
  description: 'Courtesy credit',
  line_items: [],
  live_mode: false,
  reason: 'goodwill',
  reference_id: 'credit_note_reference_123',
  status: 'issued',
  ...overrides,
})

export const billingCreditBalanceFixture = (overrides: Record<string, unknown> = {}) => ({
  balance: 500,
  conjoin_account_id: 'account_123',
  conjoin_project_id: 'project_123',
  credit_balance_id: 'credit_balance_123',
  currency: 'GHS',
  customer_id: CUSTOMER_ID,
  date_created: DATE_CREATED,
  date_updated: DATE_UPDATED,
  live_mode: false,
  ...overrides,
})

export const billingCreditWalletFixture = (overrides: Record<string, unknown> = {}) => ({
  auto_topup: {
    enabled: false,
    threshold: 0,
    topup_amount: 0,
  },
  balance: 1000,
  conjoin_account_id: 'account_123',
  conjoin_project_id: 'project_123',
  credit_value: 1,
  currency: 'GHS',
  customer_id: CUSTOMER_ID,
  date_created: DATE_CREATED,
  date_updated: DATE_UPDATED,
  is_active: true,
  label: 'default',
  live_mode: false,
  wallet_id: WALLET_ID,
  ...overrides,
})

export const billingCreditGrantFixture = (overrides: Record<string, unknown> = {}) => ({
  amount: 100,
  amount_remaining: 100,
  conjoin_account_id: 'account_123',
  conjoin_project_id: 'project_123',
  customer_id: CUSTOMER_ID,
  date_created: DATE_CREATED,
  date_updated: DATE_UPDATED,
  grant_id: 'credit_grant_123',
  is_active: true,
  live_mode: false,
  source: 'manual',
  wallet_id: WALLET_ID,
  ...overrides,
})

export const billingDiscountFixture = (overrides: Record<string, unknown> = {}) => ({
  conjoin_account_id: 'account_123',
  conjoin_project_id: 'project_123',
  coupon_id: COUPON_ID,
  currency: 'GHS',
  customer_id: CUSTOMER_ID,
  cycles_applied: 1,
  date_created: DATE_CREATED,
  date_updated: DATE_UPDATED,
  discount_amount: 100,
  discount_id: DISCOUNT_ID,
  is_active: true,
  live_mode: false,
  reference_id: 'discount_reference_123',
  start_date: DATE_CREATED,
  ...overrides,
})

export const billingInvoiceFixture = (overrides: Record<string, unknown> = {}) => ({
  amount_due: 1000,
  amount_paid: 0,
  amount_remaining: 1000,
  currency: 'GHS',
  customer_id: CUSTOMER_ID,
  invoice_id: INVOICE_ID,
  invoice_number: 'INV-0001',
  invoicing_option: 'manual_finalisation',
  is_paid: false,
  is_paid_without_charge: false,
  line_items: [],
  price_ids: [PRICE_ID],
  reference_id: 'invoice_reference_123',
  retry_count: 0,
  status: 'draft',
  subtotal: 1000,
  tax_amount: 0,
  ...overrides,
})

export const billingPaymentIntentFixture = (overrides: Record<string, unknown> = {}) => ({
  amount: 1000,
  currency: 'GHS',
  date_created: DATE_CREATED,
  date_updated: DATE_UPDATED,
  entity_id: ENTITY_ID,
  payment_intent_id: PAYMENT_INTENT_ID,
  reference_id: 'payment_intent_reference_123',
  status: 'requires_payment_method',
  ...overrides,
})

export const billingPaymentMethodFixture = (overrides: Record<string, unknown> = {}) => ({
  customer_id: CUSTOMER_ID,
  date_created: DATE_CREATED,
  date_updated: DATE_UPDATED,
  entity_id: ENTITY_ID,
  is_active: true,
  is_default: true,
  payment_method_id: PAYMENT_METHOD_ID,
  reference_id: 'payment_method_reference_123',
  ...overrides,
})

export const billingReceiptFixture = (overrides: Record<string, unknown> = {}) => ({
  amount: 1000,
  charge_id: CHARGE_ID,
  currency: 'GHS',
  customer_id: CUSTOMER_ID,
  date_created: DATE_CREATED,
  date_deleted: null,
  date_updated: DATE_UPDATED,
  entity_id: ENTITY_ID,
  error_reason: null,
  pdf_url: 'https://example.com/receipt.pdf',
  receipt_id: RECEIPT_ID,
  status: 'ready',
  ...overrides,
})

export const billingRefundFixture = (overrides: Record<string, unknown> = {}) => ({
  amount: 500,
  charge_id: CHARGE_ID,
  currency: 'GHS',
  date_created: DATE_CREATED,
  date_updated: DATE_UPDATED,
  entity_id: ENTITY_ID,
  fulfilment_type: 'cash',
  reference_id: 'refund_reference_123',
  refund_id: REFUND_ID,
  status: 'pending',
  ...overrides,
})
