import { expect } from 'vitest'
import { createAuthAccounts } from '../../../src/auth'
import { conjoinList, conjoinSuccess } from '../contract-server/response-fixtures'
import {
  ACCOUNT_ID,
  APP_ID,
  authAccountFixture,
  authCredentialFixture,
  authMembershipFixture,
  CREDENTIAL_ID,
  describeAuthSdkContractCases,
  ORGANIZATION_ID,
  REQUEST_ID,
} from './auth-test-utils'

const accountCreateBody = {
  metadata: { source: 'contract' },
  name: 'Auth Account',
  primary_email: 'owner@example.com',
  primary_phone: '+2335550100',
  reference_id: 'account_ref_123',
}
const accountUpdateBody = { name: 'Renamed Account' }
const metadataBody = { metadata: { plan: 'enterprise' } }
const statusBody = { status: 'inactive' as const }
const emailBody = { email: 'secondary@example.com', set_as_primary: true }
const phoneBody = { phone: '+2335550101', set_as_primary: true }
const removeEmailBody = { email: 'secondary@example.com', primary_email: 'owner@example.com' }
const removePhoneBody = { phone: '+2335550101', primary_phone: '+2335550100' }
const roleBody = { role_key: 'admin' }
const verifyCredentialBody = { credential_type: 'password' as const, credential_value: 'correct horse battery staple' }
const verifyTotpBody = { code: '123456' }
const removeCredentialBody = { credential_id: CREDENTIAL_ID }
const deleteBody = { permanent: false }
const customAttributesBody = { custom_attributes: { tier: 'enterprise', seats: 10 } }
const mergeBody = {
  source_account_id: 'auth_account_source_123',
  target_account_id: ACCOUNT_ID,
  strategy: 'auto_safe' as const,
}
describeAuthSdkContractCases('Auth account SDK contract integration', [
  {
    name: 'creates an auth account',
    method: 'POST',
    path: '/v1/auth/account/{app_id}/account/create',
    expectedBody: accountCreateBody,
    expectedPath: `/v1/auth/account/${APP_ID}/account/create`,
    expectedPathParams: { app_id: APP_ID },
    response: conjoinSuccess(authAccountFixture(), { requestId: REQUEST_ID, status: 201 }),
    run: context => createAuthAccounts(context.client).create(APP_ID, accountCreateBody),
    assertResult: result => expect(result).toEqual(authAccountFixture()),
  },
  {
    name: 'reads an auth account',
    method: 'GET',
    path: '/v1/auth/account/{app_id}/account/{account_id}',
    expectedPath: `/v1/auth/account/${APP_ID}/account/${ACCOUNT_ID}`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinSuccess(authAccountFixture(), { requestId: REQUEST_ID }),
    run: context => createAuthAccounts(context.client).read(APP_ID, ACCOUNT_ID),
    assertResult: result => expect(result).toEqual(authAccountFixture()),
  },
  {
    name: 'lists auth accounts',
    method: 'GET',
    path: '/v1/auth/account/account',
    expectedQuery: {
      'cursor[next]': 'cursor_next_123',
      limit: '2',
      'query[status]': 'active',
      'sort[date_created]': 'desc',
    },
    expectedRawBody: '',
    response: conjoinList([authAccountFixture()], { cursor: { next: 'cursor_next_123' }, requestId: REQUEST_ID }),
    run: context =>
      createAuthAccounts(context.client).list({
        cursor: { next: 'cursor_next_123' },
        limit: 2,
        query: { status: 'active' },
        sort: { date_created: 'desc' },
      }),
    assertResult: result =>
      expect(result).toEqual({
        success: true,
        data: [authAccountFixture()],
        cursor: { next: 'cursor_next_123' },
        status: 200,
      }),
  },
  {
    name: 'counts auth accounts',
    method: 'GET',
    path: '/v1/auth/account/account/count',
    expectedQuery: { account_id: ACCOUNT_ID, app_id: APP_ID, status: 'active' },
    expectedRawBody: '',
    response: conjoinSuccess({ count: 1 }, { requestId: REQUEST_ID }),
    run: context =>
      createAuthAccounts(context.client).count({ account_id: ACCOUNT_ID, app_id: APP_ID, status: 'active' }),
    assertResult: result => expect(result).toEqual({ count: 1 }),
  },
  {
    name: 'updates an auth account',
    method: 'PATCH',
    path: '/v1/auth/account/{app_id}/account/{account_id}/update',
    expectedBody: accountUpdateBody,
    expectedPath: `/v1/auth/account/${APP_ID}/account/${ACCOUNT_ID}/update`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinSuccess(authAccountFixture({ name: 'Renamed Account' }), { requestId: REQUEST_ID }),
    run: context => createAuthAccounts(context.client).update(APP_ID, ACCOUNT_ID, accountUpdateBody),
    assertResult: result => expect(result).toEqual(authAccountFixture({ name: 'Renamed Account' })),
  },
  {
    name: 'updates auth account metadata',
    method: 'PATCH',
    path: '/v1/auth/account/{app_id}/account/{account_id}/metadata/update',
    expectedBody: metadataBody,
    expectedPath: `/v1/auth/account/${APP_ID}/account/${ACCOUNT_ID}/metadata/update`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinSuccess(authAccountFixture({ metadata: metadataBody.metadata }), { requestId: REQUEST_ID }),
    run: context => createAuthAccounts(context.client).updateMetadata(APP_ID, ACCOUNT_ID, metadataBody),
    assertResult: result => expect(result).toEqual(authAccountFixture({ metadata: metadataBody.metadata })),
  },
  {
    name: 'updates auth account status',
    method: 'PATCH',
    path: '/v1/auth/account/{app_id}/account/{account_id}/status/update',
    expectedBody: statusBody,
    expectedPath: `/v1/auth/account/${APP_ID}/account/${ACCOUNT_ID}/status/update`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinSuccess(authAccountFixture({ status: 'inactive' }), { requestId: REQUEST_ID }),
    run: context => createAuthAccounts(context.client).updateStatus(APP_ID, ACCOUNT_ID, statusBody),
    assertResult: result => expect(result).toEqual(authAccountFixture({ status: 'inactive' })),
  },
  {
    name: 'adds an auth account email',
    method: 'POST',
    path: '/v1/auth/account/{app_id}/account/{account_id}/email/add',
    expectedBody: emailBody,
    expectedPath: `/v1/auth/account/${APP_ID}/account/${ACCOUNT_ID}/email/add`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinSuccess(authAccountFixture({ primary_email: 'secondary@example.com' }), { requestId: REQUEST_ID }),
    run: context => createAuthAccounts(context.client).addEmail(APP_ID, ACCOUNT_ID, emailBody),
    assertResult: result => expect(result).toEqual(authAccountFixture({ primary_email: 'secondary@example.com' })),
  },
  {
    name: 'adds an auth account phone',
    method: 'POST',
    path: '/v1/auth/account/{app_id}/account/{account_id}/phone/add',
    expectedBody: phoneBody,
    expectedPath: `/v1/auth/account/${APP_ID}/account/${ACCOUNT_ID}/phone/add`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinSuccess(authAccountFixture({ primary_phone: '+2335550101' }), { requestId: REQUEST_ID }),
    run: context => createAuthAccounts(context.client).addPhone(APP_ID, ACCOUNT_ID, phoneBody),
    assertResult: result => expect(result).toEqual(authAccountFixture({ primary_phone: '+2335550101' })),
  },
  {
    name: 'removes an auth account email',
    method: 'POST',
    path: '/v1/auth/account/{app_id}/account/{account_id}/email/remove',
    expectedBody: removeEmailBody,
    expectedPath: `/v1/auth/account/${APP_ID}/account/${ACCOUNT_ID}/email/remove`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinSuccess(authAccountFixture(), { requestId: REQUEST_ID }),
    run: context => createAuthAccounts(context.client).removeEmail(APP_ID, ACCOUNT_ID, removeEmailBody),
    assertResult: result => expect(result).toEqual(authAccountFixture()),
  },
  {
    name: 'removes an auth account phone',
    method: 'POST',
    path: '/v1/auth/account/{app_id}/account/{account_id}/phone/remove',
    expectedBody: removePhoneBody,
    expectedPath: `/v1/auth/account/${APP_ID}/account/${ACCOUNT_ID}/phone/remove`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinSuccess(authAccountFixture(), { requestId: REQUEST_ID }),
    run: context => createAuthAccounts(context.client).removePhone(APP_ID, ACCOUNT_ID, removePhoneBody),
    assertResult: result => expect(result).toEqual(authAccountFixture()),
  },
  {
    name: 'lists account organization memberships',
    method: 'GET',
    path: '/v1/auth/account/{app_id}/account/{account_id}/organizations',
    expectedPath: `/v1/auth/account/${APP_ID}/account/${ACCOUNT_ID}/organizations`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    expectedQuery: { limit: '1', 'sort[date_created]': 'desc' },
    expectedRawBody: '',
    response: conjoinList([authMembershipFixture()], { requestId: REQUEST_ID }),
    run: context =>
      createAuthAccounts(context.client).listOrganizationMemberships(APP_ID, ACCOUNT_ID, {
        limit: 1,
        sort: { date_created: 'desc' },
      }),
    assertResult: result => expect(result).toEqual({ success: true, data: [authMembershipFixture()], status: 200 }),
  },
  {
    name: 'grants an organization account role',
    method: 'POST',
    path: '/v1/auth/account/{app_id}/organization/{organization_id}/account/{account_id}/role/grant',
    expectedBody: roleBody,
    expectedPath: `/v1/auth/account/${APP_ID}/organization/${ORGANIZATION_ID}/account/${ACCOUNT_ID}/role/grant`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID, organization_id: ORGANIZATION_ID },
    response: conjoinSuccess(authAccountFixture(), { requestId: REQUEST_ID }),
    run: context => createAuthAccounts(context.client).grantOrgRole(APP_ID, ORGANIZATION_ID, ACCOUNT_ID, roleBody),
    assertResult: result => expect(result).toEqual(authAccountFixture()),
  },
  {
    name: 'revokes an organization account role',
    method: 'POST',
    path: '/v1/auth/account/{app_id}/organization/{organization_id}/account/{account_id}/role/revoke',
    expectedBody: roleBody,
    expectedPath: `/v1/auth/account/${APP_ID}/organization/${ORGANIZATION_ID}/account/${ACCOUNT_ID}/role/revoke`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID, organization_id: ORGANIZATION_ID },
    response: conjoinSuccess(authAccountFixture(), { requestId: REQUEST_ID }),
    run: context => createAuthAccounts(context.client).revokeOrgRole(APP_ID, ORGANIZATION_ID, ACCOUNT_ID, roleBody),
    assertResult: result => expect(result).toEqual(authAccountFixture()),
  },
  {
    name: 'verifies an auth account credential',
    method: 'POST',
    path: '/v1/auth/account/{app_id}/account/{account_id}/credential/verify',
    expectedBody: verifyCredentialBody,
    expectedPath: `/v1/auth/account/${APP_ID}/account/${ACCOUNT_ID}/credential/verify`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinSuccess(authCredentialFixture(), { requestId: REQUEST_ID }),
    run: context => createAuthAccounts(context.client).verifyCredential(APP_ID, ACCOUNT_ID, verifyCredentialBody),
    assertResult: result => expect(result).toEqual(authCredentialFixture()),
  },
  {
    name: 'verifies an auth account TOTP credential',
    method: 'POST',
    path: '/v1/auth/account/{app_id}/account/{account_id}/credential/mfa/totp/verify',
    expectedBody: verifyTotpBody,
    expectedPath: `/v1/auth/account/${APP_ID}/account/${ACCOUNT_ID}/credential/mfa/totp/verify`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinSuccess(authCredentialFixture({ kind: 'mfa_totp' }), { requestId: REQUEST_ID }),
    run: context => createAuthAccounts(context.client).verifyCredentialMfaTotp(APP_ID, ACCOUNT_ID, verifyTotpBody),
    assertResult: result => expect(result).toEqual(authCredentialFixture({ kind: 'mfa_totp' })),
  },
  {
    name: 'counts auth account credentials',
    method: 'GET',
    path: '/v1/auth/account/{app_id}/account/{account_id}/credential/count',
    expectedPath: `/v1/auth/account/${APP_ID}/account/${ACCOUNT_ID}/credential/count`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    expectedQuery: { credential_id: CREDENTIAL_ID, credential_type: 'password' },
    expectedRawBody: '',
    response: conjoinSuccess({ count: 1 }, { requestId: REQUEST_ID }),
    run: context =>
      createAuthAccounts(context.client).countCredentials(APP_ID, ACCOUNT_ID, {
        credential_id: CREDENTIAL_ID,
        credential_type: 'password',
      }),
    assertResult: result => expect(result).toEqual({ count: 1 }),
  },
  {
    name: 'lists auth account credentials',
    method: 'GET',
    path: '/v1/auth/account/{app_id}/account/{account_id}/credential',
    expectedPath: `/v1/auth/account/${APP_ID}/account/${ACCOUNT_ID}/credential`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    expectedQuery: { limit: '1', 'query[credential_type]': 'password' },
    expectedRawBody: '',
    response: conjoinList([authCredentialFixture()], { requestId: REQUEST_ID }),
    run: context =>
      createAuthAccounts(context.client).listCredentials(APP_ID, ACCOUNT_ID, {
        limit: 1,
        query: { credential_type: 'password' },
      }),
    assertResult: result => expect(result).toEqual({ success: true, data: [authCredentialFixture()], status: 200 }),
  },
  {
    name: 'removes an auth account credential',
    method: 'POST',
    path: '/v1/auth/account/{app_id}/account/{account_id}/credential/remove',
    expectedBody: removeCredentialBody,
    expectedPath: `/v1/auth/account/${APP_ID}/account/${ACCOUNT_ID}/credential/remove`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinSuccess(authCredentialFixture({ status: 'removed' }), { requestId: REQUEST_ID }),
    run: context => createAuthAccounts(context.client).removeCredential(APP_ID, ACCOUNT_ID, removeCredentialBody),
    assertResult: result => expect(result).toEqual(authCredentialFixture({ status: 'removed' })),
  },
  {
    name: 'grants an auth account global role',
    method: 'POST',
    path: '/v1/auth/account/{app_id}/account/{account_id}/global-role/grant',
    expectedBody: roleBody,
    expectedPath: `/v1/auth/account/${APP_ID}/account/${ACCOUNT_ID}/global-role/grant`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinSuccess(authAccountFixture(), { requestId: REQUEST_ID }),
    run: context => createAuthAccounts(context.client).grantGlobalRole(APP_ID, ACCOUNT_ID, roleBody),
    assertResult: result => expect(result).toEqual(authAccountFixture()),
  },
  {
    name: 'revokes an auth account global role',
    method: 'POST',
    path: '/v1/auth/account/{app_id}/account/{account_id}/global-role/revoke',
    expectedBody: roleBody,
    expectedPath: `/v1/auth/account/${APP_ID}/account/${ACCOUNT_ID}/global-role/revoke`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinSuccess(authAccountFixture(), { requestId: REQUEST_ID }),
    run: context => createAuthAccounts(context.client).revokeGlobalRole(APP_ID, ACCOUNT_ID, roleBody),
    assertResult: result => expect(result).toEqual(authAccountFixture()),
  },
  {
    name: 'deletes an auth account',
    method: 'POST',
    path: '/v1/auth/account/{app_id}/account/{account_id}/delete',
    expectedBody: deleteBody,
    expectedPath: `/v1/auth/account/${APP_ID}/account/${ACCOUNT_ID}/delete`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinSuccess(authAccountFixture({ status: 'deleted' }), { requestId: REQUEST_ID }),
    run: context => createAuthAccounts(context.client).delete(APP_ID, ACCOUNT_ID, deleteBody),
    assertResult: result => expect(result).toEqual(authAccountFixture({ status: 'deleted' })),
  },
  {
    name: 'exports an auth account',
    method: 'GET',
    path: '/v1/auth/account/{app_id}/account/{account_id}/export',
    expectedPath: `/v1/auth/account/${APP_ID}/account/${ACCOUNT_ID}/export`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinSuccess(authAccountFixture({ export_id: 'export_123' }), { requestId: REQUEST_ID }),
    run: context => createAuthAccounts(context.client).export(APP_ID, ACCOUNT_ID),
    assertResult: result => expect(result).toEqual(authAccountFixture({ export_id: 'export_123' })),
  },
  {
    name: 'sets auth account custom attributes',
    method: 'PUT',
    path: '/v1/auth/account/{app_id}/account/{account_id}/custom-attributes',
    expectedBody: customAttributesBody,
    expectedPath: `/v1/auth/account/${APP_ID}/account/${ACCOUNT_ID}/custom-attributes`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinSuccess(authAccountFixture({ custom_attributes: customAttributesBody.custom_attributes }), {
      requestId: REQUEST_ID,
    }),
    run: context => createAuthAccounts(context.client).setCustomAttributes(APP_ID, ACCOUNT_ID, customAttributesBody),
    assertResult: result =>
      expect(result).toEqual(authAccountFixture({ custom_attributes: customAttributesBody.custom_attributes })),
  },
  {
    name: 'merges auth accounts',
    method: 'POST',
    path: '/v1/auth/account/{app_id}/account/merge',
    expectedBody: mergeBody,
    expectedPath: `/v1/auth/account/${APP_ID}/account/merge`,
    expectedPathParams: { app_id: APP_ID },
    response: conjoinSuccess(
      { source_account_id: 'auth_account_source_123', status: 'merged', target_account_id: ACCOUNT_ID },
      { requestId: REQUEST_ID },
    ),
    run: context => createAuthAccounts(context.client).merge(APP_ID, mergeBody),
    assertResult: result =>
      expect(result).toEqual({
        source_account_id: 'auth_account_source_123',
        status: 'merged',
        target_account_id: ACCOUNT_ID,
      }),
  },
])
