import { expect } from 'vitest'
import { createAuthCredentials, createAuthPasskeys } from '../../../src/auth'
import { conjoinList, conjoinSuccess } from '../contract-server/response-fixtures'
import {
  ACCOUNT_ID,
  APP_ID,
  authCredentialFixture,
  CREDENTIAL_ID,
  describeAuthSdkContractCases,
  REQUEST_ID,
} from './auth-test-utils'

const passwordBody = { password: 'correct horse battery staple' }
const rotatePasswordBody = {
  current_password: 'correct horse battery staple',
  new_password: 'better horse battery staple',
}
const enrollTotpBody = {
  account_label: 'owner@example.com',
  issuer: 'Conjoin',
  recovery_code_count: 8,
  recovery_code_length: 12,
}
const codeBody = { code: '123456' }
const smsBody = { phone: '+2335550100' }
const emailBody = { email: 'owner@example.com' }
const issueApiKeyBody = { label: 'Primary API key', prefix: 'ck', scopes: ['project.read'], test_mode: true }
const apiKeyBody = { public_key_id: 'public_key_123' }
const updateApiKeyBody = { allowed_ips: ['127.0.0.1'], label: 'Renamed API key' }
const passkeyRegistrationBody = { user_handle: 'owner@example.com' }
const passkeyAttestationBody = { attestation_response: { id: 'attestation_123' } }
const passkeyAssertionBody = { assertion_response: { id: 'assertion_123' } }

describeAuthSdkContractCases('Auth credential SDK contract integration', [
  {
    name: 'creates a password credential',
    method: 'POST',
    path: '/v1/auth/credential/{app_id}/account/{account_id}/credential/password/create',
    expectedBody: passwordBody,
    expectedPath: `/v1/auth/credential/${APP_ID}/account/${ACCOUNT_ID}/credential/password/create`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinSuccess(authCredentialFixture(), { requestId: REQUEST_ID, status: 201 }),
    run: context => createAuthCredentials(context.client).createPassword(APP_ID, ACCOUNT_ID, passwordBody),
    assertResult: result => expect(result).toEqual(authCredentialFixture()),
  },
  {
    name: 'rotates a password credential',
    method: 'POST',
    path: '/v1/auth/credential/{app_id}/account/{account_id}/credential/password/rotate',
    expectedBody: rotatePasswordBody,
    expectedPath: `/v1/auth/credential/${APP_ID}/account/${ACCOUNT_ID}/credential/password/rotate`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinSuccess(authCredentialFixture(), { requestId: REQUEST_ID }),
    run: context => createAuthCredentials(context.client).rotatePassword(APP_ID, ACCOUNT_ID, rotatePasswordBody),
    assertResult: result => expect(result).toEqual(authCredentialFixture()),
  },
  {
    name: 'enrolls a TOTP credential',
    method: 'POST',
    path: '/v1/auth/credential/{app_id}/account/{account_id}/credential/mfa/totp/enroll',
    expectedBody: enrollTotpBody,
    expectedPath: `/v1/auth/credential/${APP_ID}/account/${ACCOUNT_ID}/credential/mfa/totp/enroll`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinSuccess(authCredentialFixture({ kind: 'mfa_totp' }), { requestId: REQUEST_ID, status: 201 }),
    run: context => createAuthCredentials(context.client).enrollTotp(APP_ID, ACCOUNT_ID, enrollTotpBody),
    assertResult: result => expect(result).toEqual(authCredentialFixture({ kind: 'mfa_totp' })),
  },
  {
    name: 'activates a TOTP credential',
    method: 'POST',
    path: '/v1/auth/credential/{app_id}/account/{account_id}/credential/mfa/totp/activate',
    expectedBody: codeBody,
    expectedPath: `/v1/auth/credential/${APP_ID}/account/${ACCOUNT_ID}/credential/mfa/totp/activate`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinSuccess(authCredentialFixture({ kind: 'mfa_totp' }), { requestId: REQUEST_ID }),
    run: context => createAuthCredentials(context.client).activateTotp(APP_ID, ACCOUNT_ID, codeBody),
    assertResult: result => expect(result).toEqual(authCredentialFixture({ kind: 'mfa_totp' })),
  },
  {
    name: 'rotates TOTP recovery codes',
    method: 'POST',
    path: '/v1/auth/credential/{app_id}/account/{account_id}/credential/mfa/totp/recovery/rotate',
    expectedBody: enrollTotpBody,
    expectedPath: `/v1/auth/credential/${APP_ID}/account/${ACCOUNT_ID}/credential/mfa/totp/recovery/rotate`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinSuccess(authCredentialFixture({ kind: 'mfa_totp' }), { requestId: REQUEST_ID }),
    run: context => createAuthCredentials(context.client).rotateTotpRecoveryCodes(APP_ID, ACCOUNT_ID, enrollTotpBody),
    assertResult: result => expect(result).toEqual(authCredentialFixture({ kind: 'mfa_totp' })),
  },
  {
    name: 'consumes a TOTP recovery code',
    method: 'POST',
    path: '/v1/auth/credential/{app_id}/account/{account_id}/credential/mfa/totp/recovery/consume',
    expectedBody: codeBody,
    expectedPath: `/v1/auth/credential/${APP_ID}/account/${ACCOUNT_ID}/credential/mfa/totp/recovery/consume`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinSuccess(authCredentialFixture({ kind: 'mfa_totp' }), { requestId: REQUEST_ID }),
    run: context => createAuthCredentials(context.client).consumeTotpRecoveryCode(APP_ID, ACCOUNT_ID, codeBody),
    assertResult: result => expect(result).toEqual(authCredentialFixture({ kind: 'mfa_totp' })),
  },
  {
    name: 'enrolls an SMS MFA credential',
    method: 'POST',
    path: '/v1/auth/credential/{app_id}/account/{account_id}/credential/mfa/sms/enroll',
    expectedBody: smsBody,
    expectedPath: `/v1/auth/credential/${APP_ID}/account/${ACCOUNT_ID}/credential/mfa/sms/enroll`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinSuccess(authCredentialFixture({ kind: 'mfa_sms' }), { requestId: REQUEST_ID, status: 201 }),
    run: context => createAuthCredentials(context.client).enrollSmsMfa(APP_ID, ACCOUNT_ID, smsBody),
    assertResult: result => expect(result).toEqual(authCredentialFixture({ kind: 'mfa_sms' })),
  },
  {
    name: 'activates an SMS MFA credential',
    method: 'POST',
    path: '/v1/auth/credential/{app_id}/account/{account_id}/credential/mfa/sms/activate',
    expectedBody: codeBody,
    expectedPath: `/v1/auth/credential/${APP_ID}/account/${ACCOUNT_ID}/credential/mfa/sms/activate`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinSuccess(authCredentialFixture({ kind: 'mfa_sms' }), { requestId: REQUEST_ID }),
    run: context => createAuthCredentials(context.client).activateSmsMfa(APP_ID, ACCOUNT_ID, codeBody),
    assertResult: result => expect(result).toEqual(authCredentialFixture({ kind: 'mfa_sms' })),
  },
  {
    name: 'verifies an SMS MFA credential',
    method: 'POST',
    path: '/v1/auth/credential/{app_id}/account/{account_id}/credential/mfa/sms/verify',
    expectedBody: codeBody,
    expectedPath: `/v1/auth/credential/${APP_ID}/account/${ACCOUNT_ID}/credential/mfa/sms/verify`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinSuccess(authCredentialFixture({ kind: 'mfa_sms' }), { requestId: REQUEST_ID }),
    run: context => createAuthCredentials(context.client).verifySmsMfa(APP_ID, ACCOUNT_ID, codeBody),
    assertResult: result => expect(result).toEqual(authCredentialFixture({ kind: 'mfa_sms' })),
  },
  {
    name: 'sends an SMS MFA challenge',
    method: 'POST',
    path: '/v1/auth/credential/{app_id}/account/{account_id}/credential/mfa/sms/challenge',
    expectedPath: `/v1/auth/credential/${APP_ID}/account/${ACCOUNT_ID}/credential/mfa/sms/challenge`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinSuccess(authCredentialFixture({ kind: 'mfa_sms' }), { requestId: REQUEST_ID }),
    run: context => createAuthCredentials(context.client).sendSmsMfaChallenge(APP_ID, ACCOUNT_ID),
    assertResult: result => expect(result).toEqual(authCredentialFixture({ kind: 'mfa_sms' })),
  },
  {
    name: 'enrolls an email MFA credential',
    method: 'POST',
    path: '/v1/auth/credential/{app_id}/account/{account_id}/credential/mfa/email/enroll',
    expectedBody: emailBody,
    expectedPath: `/v1/auth/credential/${APP_ID}/account/${ACCOUNT_ID}/credential/mfa/email/enroll`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinSuccess(authCredentialFixture({ kind: 'mfa_email' }), { requestId: REQUEST_ID, status: 201 }),
    run: context => createAuthCredentials(context.client).enrollEmailMfa(APP_ID, ACCOUNT_ID, emailBody),
    assertResult: result => expect(result).toEqual(authCredentialFixture({ kind: 'mfa_email' })),
  },
  {
    name: 'activates an email MFA credential',
    method: 'POST',
    path: '/v1/auth/credential/{app_id}/account/{account_id}/credential/mfa/email/activate',
    expectedBody: codeBody,
    expectedPath: `/v1/auth/credential/${APP_ID}/account/${ACCOUNT_ID}/credential/mfa/email/activate`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinSuccess(authCredentialFixture({ kind: 'mfa_email' }), { requestId: REQUEST_ID }),
    run: context => createAuthCredentials(context.client).activateEmailMfa(APP_ID, ACCOUNT_ID, codeBody),
    assertResult: result => expect(result).toEqual(authCredentialFixture({ kind: 'mfa_email' })),
  },
  {
    name: 'verifies an email MFA credential',
    method: 'POST',
    path: '/v1/auth/credential/{app_id}/account/{account_id}/credential/mfa/email/verify',
    expectedBody: codeBody,
    expectedPath: `/v1/auth/credential/${APP_ID}/account/${ACCOUNT_ID}/credential/mfa/email/verify`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinSuccess(authCredentialFixture({ kind: 'mfa_email' }), { requestId: REQUEST_ID }),
    run: context => createAuthCredentials(context.client).verifyEmailMfa(APP_ID, ACCOUNT_ID, codeBody),
    assertResult: result => expect(result).toEqual(authCredentialFixture({ kind: 'mfa_email' })),
  },
  {
    name: 'sends an email MFA challenge',
    method: 'POST',
    path: '/v1/auth/credential/{app_id}/account/{account_id}/credential/mfa/email/challenge',
    expectedPath: `/v1/auth/credential/${APP_ID}/account/${ACCOUNT_ID}/credential/mfa/email/challenge`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinSuccess(authCredentialFixture({ kind: 'mfa_email' }), { requestId: REQUEST_ID }),
    run: context => createAuthCredentials(context.client).sendEmailMfaChallenge(APP_ID, ACCOUNT_ID),
    assertResult: result => expect(result).toEqual(authCredentialFixture({ kind: 'mfa_email' })),
  },
  {
    name: 'reads API key credential usage',
    method: 'GET',
    path: '/v1/auth/credential/{app_id}/account/{account_id}/credentials/api-keys/usage-stats',
    expectedPath: `/v1/auth/credential/${APP_ID}/account/${ACCOUNT_ID}/credentials/api-keys/usage-stats`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinSuccess(authCredentialFixture({ kind: 'api_key' }), { requestId: REQUEST_ID }),
    run: context => createAuthCredentials(context.client).readApiKeyUsage(APP_ID, ACCOUNT_ID),
    assertResult: result => expect(result).toEqual(authCredentialFixture({ kind: 'api_key' })),
  },
  {
    name: 'issues an API key credential',
    method: 'POST',
    path: '/v1/auth/credential/{app_id}/account/{account_id}/credential/api-key/issue',
    expectedBody: issueApiKeyBody,
    expectedPath: `/v1/auth/credential/${APP_ID}/account/${ACCOUNT_ID}/credential/api-key/issue`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinSuccess(authCredentialFixture({ kind: 'api_key' }), { requestId: REQUEST_ID, status: 201 }),
    run: context => createAuthCredentials(context.client).issueApiKey(APP_ID, ACCOUNT_ID, issueApiKeyBody),
    assertResult: result => expect(result).toEqual(authCredentialFixture({ kind: 'api_key' })),
  },
  {
    name: 'rotates an API key credential',
    method: 'POST',
    path: '/v1/auth/credential/{app_id}/account/{account_id}/credential/api-key/rotate',
    expectedBody: apiKeyBody,
    expectedPath: `/v1/auth/credential/${APP_ID}/account/${ACCOUNT_ID}/credential/api-key/rotate`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinSuccess(authCredentialFixture({ kind: 'api_key' }), { requestId: REQUEST_ID }),
    run: context => createAuthCredentials(context.client).rotateApiKey(APP_ID, ACCOUNT_ID, apiKeyBody),
    assertResult: result => expect(result).toEqual(authCredentialFixture({ kind: 'api_key' })),
  },
  {
    name: 'revokes an API key credential',
    method: 'POST',
    path: '/v1/auth/credential/{app_id}/account/{account_id}/credential/api-key/revoke',
    expectedBody: apiKeyBody,
    expectedPath: `/v1/auth/credential/${APP_ID}/account/${ACCOUNT_ID}/credential/api-key/revoke`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinSuccess(authCredentialFixture({ kind: 'api_key', status: 'revoked' }), { requestId: REQUEST_ID }),
    run: context => createAuthCredentials(context.client).revokeApiKey(APP_ID, ACCOUNT_ID, apiKeyBody),
    assertResult: result => expect(result).toEqual(authCredentialFixture({ kind: 'api_key', status: 'revoked' })),
  },
  {
    name: 'updates an API key credential',
    method: 'PATCH',
    path: '/v1/auth/credential/{app_id}/account/{account_id}/credential/api-key/{credential_id}/update',
    expectedBody: updateApiKeyBody,
    expectedPath: `/v1/auth/credential/${APP_ID}/account/${ACCOUNT_ID}/credential/api-key/${CREDENTIAL_ID}/update`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID, credential_id: CREDENTIAL_ID },
    response: conjoinSuccess(authCredentialFixture({ kind: 'api_key' }), { requestId: REQUEST_ID }),
    run: context =>
      createAuthCredentials(context.client).updateApiKey(APP_ID, ACCOUNT_ID, CREDENTIAL_ID, updateApiKeyBody),
    assertResult: result => expect(result).toEqual(authCredentialFixture({ kind: 'api_key' })),
  },
  {
    name: 'starts passkey registration through credentials',
    method: 'POST',
    path: '/v1/auth/credential/{app_id}/account/{account_id}/credential/passkey/registration/start',
    expectedBody: passkeyRegistrationBody,
    expectedPath: `/v1/auth/credential/${APP_ID}/account/${ACCOUNT_ID}/credential/passkey/registration/start`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinSuccess(authCredentialFixture({ kind: 'mfa_passkey' }), { requestId: REQUEST_ID }),
    run: context =>
      createAuthCredentials(context.client).startPasskeyRegistration(APP_ID, ACCOUNT_ID, passkeyRegistrationBody),
    assertResult: result => expect(result).toEqual(authCredentialFixture({ kind: 'mfa_passkey' })),
  },
  {
    name: 'verifies passkey registration through credentials',
    method: 'POST',
    path: '/v1/auth/credential/{app_id}/account/{account_id}/credential/passkey/registration/verify',
    expectedBody: passkeyAttestationBody,
    expectedPath: `/v1/auth/credential/${APP_ID}/account/${ACCOUNT_ID}/credential/passkey/registration/verify`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinSuccess(authCredentialFixture({ kind: 'mfa_passkey' }), { requestId: REQUEST_ID, status: 201 }),
    run: context =>
      createAuthCredentials(context.client).verifyPasskeyRegistration(APP_ID, ACCOUNT_ID, passkeyAttestationBody),
    assertResult: result => expect(result).toEqual(authCredentialFixture({ kind: 'mfa_passkey' })),
  },
  {
    name: 'starts passkey authentication through credentials',
    method: 'POST',
    path: '/v1/auth/credential/{app_id}/account/{account_id}/credential/passkey/authentication/start',
    expectedPath: `/v1/auth/credential/${APP_ID}/account/${ACCOUNT_ID}/credential/passkey/authentication/start`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinSuccess(authCredentialFixture({ kind: 'mfa_passkey' }), { requestId: REQUEST_ID }),
    run: context => createAuthCredentials(context.client).startPasskeyentication(APP_ID, ACCOUNT_ID),
    assertResult: result => expect(result).toEqual(authCredentialFixture({ kind: 'mfa_passkey' })),
  },
  {
    name: 'verifies passkey authentication through credentials',
    method: 'POST',
    path: '/v1/auth/credential/{app_id}/account/{account_id}/credential/passkey/authentication/verify',
    expectedBody: passkeyAssertionBody,
    expectedPath: `/v1/auth/credential/${APP_ID}/account/${ACCOUNT_ID}/credential/passkey/authentication/verify`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinSuccess(authCredentialFixture({ kind: 'mfa_passkey' }), { requestId: REQUEST_ID }),
    run: context =>
      createAuthCredentials(context.client).verifyPasskeyentication(APP_ID, ACCOUNT_ID, passkeyAssertionBody),
    assertResult: result => expect(result).toEqual(authCredentialFixture({ kind: 'mfa_passkey' })),
  },
])

describeAuthSdkContractCases('Auth passkey SDK contract integration', [
  {
    name: 'lists auth passkeys',
    method: 'GET',
    path: '/v1/auth/passkey/{app_id}/account/{account_id}/passkeys',
    expectedPath: `/v1/auth/passkey/${APP_ID}/account/${ACCOUNT_ID}/passkeys`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID },
    response: conjoinList([authCredentialFixture({ kind: 'mfa_passkey' })], { requestId: REQUEST_ID }),
    run: context => createAuthPasskeys(context.client).list(APP_ID, ACCOUNT_ID),
    assertResult: result =>
      expect(result).toEqual({ success: true, data: [authCredentialFixture({ kind: 'mfa_passkey' })], status: 200 }),
  },
  {
    name: 'reads an auth passkey',
    method: 'GET',
    path: '/v1/auth/passkey/{app_id}/account/{account_id}/passkeys/{credential_id}',
    expectedPath: `/v1/auth/passkey/${APP_ID}/account/${ACCOUNT_ID}/passkeys/${CREDENTIAL_ID}`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID, credential_id: CREDENTIAL_ID },
    response: conjoinSuccess(authCredentialFixture({ kind: 'mfa_passkey' }), { requestId: REQUEST_ID }),
    run: context => createAuthPasskeys(context.client).read(APP_ID, ACCOUNT_ID, CREDENTIAL_ID),
    assertResult: result => expect(result).toEqual(authCredentialFixture({ kind: 'mfa_passkey' })),
  },
  {
    name: 'deletes an auth passkey',
    method: 'DELETE',
    path: '/v1/auth/passkey/{app_id}/account/{account_id}/passkeys/{credential_id}/delete',
    expectedPath: `/v1/auth/passkey/${APP_ID}/account/${ACCOUNT_ID}/passkeys/${CREDENTIAL_ID}/delete`,
    expectedPathParams: { account_id: ACCOUNT_ID, app_id: APP_ID, credential_id: CREDENTIAL_ID },
    response: conjoinSuccess(authCredentialFixture({ kind: 'mfa_passkey', status: 'deleted' }), {
      requestId: REQUEST_ID,
    }),
    run: context => createAuthPasskeys(context.client).delete(APP_ID, ACCOUNT_ID, CREDENTIAL_ID),
    assertResult: result => expect(result).toEqual(authCredentialFixture({ kind: 'mfa_passkey', status: 'deleted' })),
  },
])
